#!/bin/bash

###############################
# Author: Muzammil
# Date: 24//06/25
#
# This scropt outputs the node health
# Version: v1
################################

echo "Print the disk space"
df -h

echo "Print the memory"
free -g

echo "print the cpu"
nproc
