#!/bin/bash

###############################
# Author: Muzammil
# Date: 24//06/25
#
# This scropt outputs the node health
# Version: v2
################################

set -x       #enables a shell mode where all executed commands are printed to the terminal.

df -h

free -g

nproc

ps -ef | grep amazon | awk '{print $2}'        #gets the process ID of amazon pocess running on your linux machine
