#!/bin/bash

###############################
# Author: Muzammil
# Date: 24//06/25
#
# This scropt outputs the node health
# Version: v2
################################

set -x       #debug mode

df -h

free -g

nproc
