#!/bin/bash

###############################
# Author: Muzammil
# Date: 24//06/25
#
# This scropt outputs the node health
# Version: v2
################################

set -x       #enables a shell mode where all executed commands are printed to the terminal.

df -h

free -g

nproc
